<?php
/**
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Beranda',
    'My-Trip' => 'Pengaturan pemesanan',
    'Check-In' => 'Check-in',
    'From' => 'Dari',
    'To' => 'Ke',
    'Email' => 'Email',
    'Profile' => 'Profil',
    'My-Profile' => 'Profil Saya',
    'One-Way' => 'Sekali Jalan',
    'Round Trip' => 'Pulang-Pergi',
    'Departure Date'=>'Keberangkatan',
    'Arrival Date'=>'Kedatangan',
    'Return Date'=>'Kembali',
    'Passangers'=>'Penumpang',
    'Class'=>'Kelas',
    'Adults (12+ years)'=>'Dewasa (12+ Tahun)',
    'Child (2-11 years)'=>'Anak-anak (2-11 Tahun)',
    'Infant (Under 2 years)' => 'Bayi (Dibawah 2 Tahun)',
    'Search' => 'CARI',
    'Booking Number'=>'Nomor Pemesanan',
    'Login' => 'Masuk',
    'Logout' => 'Keluar',
    'Register' => 'Daftar',
    'Departure'=>'Keberangkatan',
    'Arrival' => 'Kedatangan',
    'First Name' =>'Nama Depan',
    'Last Name' => 'Nama Belakang',
    'Date Of Birth' => 'Tanggal Lahir',
    'Gender' => 'Jenis Kelamin',
    'Nationality' => 'Kewarganegaraan',
    'Document Type' => 'Jenis Dokumen',
    'Document Number' => 'Nomor Dokumen',
    'Contact Details'=> 'Detail Kontak',
    'Price' => 'Harga',
    'Total Price' => 'Harga Total',
    'Adult' => 'Dewasa',
    'Child' => 'Anak-anak',
    'Infant' => 'Bayi',
    'Add Passanger' => 'Tambah Penupang',
    'Payment' => 'PEMBAYARAN',
    'Pay' => 'BAYAR',
    'Search Error' => 'Maaf kami tidak bisa menemukan halaman yang anda cari!',
    'Available' => 'Tesedia',
    'Selected'=> 'Dipilih',
    'Select' => 'PILIH',
    'ID' => 'No',
    'Occupied' => 'Tidak Tersedia',
    'Passanger Name' => 'Nama Pengunjung',
    'Check-in Note' => 'Jika anda sudah selesai memilih kursi silahkan klik tombol di bawah',
];