<?php
/**
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delete' => 'Изтрий',
    'My-Trip' => 'Моите Пътувания',
    'Check-In' => 'Чекиране',
    'Error' => 'Грешка',
    'Home' => 'Начало',
    'No' => 'Не',
    'Update' => 'Обнови',
    'View' => 'Виж',
    'Yes' => 'Да',
    'Home' => 'Начало',
    'From' => 'От',
    'To' => 'До',
    'Email' => 'Емайл',
    'Profile' => 'Профил',
    'My-Profile' => 'Моят Профил',
    'One-Way' => 'Еднопосочен',
    'Round Trip' => 'Двупосочен',
    'Departure Date'=>'заминаване',
    'Arrival Date'=>'ристигане',
    'Return Date'=>'връщане',
    'Passangers'=>'Пасажери',
    'Class'=>'Клас',
    'Adults (12+ years)'=>'Възрастни (12+ Години)',
    'Child (2-11 years)'=>'Деца (2-11 Години)',
    'Infant (Under 2 years)' => 'Кърмаче (Под 2 години)',
    'Search' => 'Търсене',
    'Booking Number'=>'Номер на резервацията',
    'Login' => 'Влизане',
    'Logout' => 'Излизане',
    'Register' => 'Регистрация',
    'Departure'=>'Напускащ',
    'Arrival' => 'Пристигащ',
    'First Name' =>'Дадено име',
    'Last Name' => 'Поселдно Име',
    'Date Of Birth' => 'Дата на раждане',
    'Gender' => 'Пол',
    'Nationality' => 'Националност',
    'Document Type' => 'Тип документ',
    'Document Number' => 'Номер на документа',
    'Contact Details'=> 'Дайтали за контакт',
    'Price' => 'Цена',
    'Total Price' => 'Общо Цена',
    'Adult' => 'Възрастен',
    'Child' => 'Дете',
    'Infant' => 'Кърмаче',
    'Add Passanger' => 'Добави пасажер',
    'Payment' => 'Плащане',
    'Pay' => 'Плати',
    'Search Error' => 'Няма полети според това което търсите!',
    'Available' => 'Свободно',
    'Selected'=> 'Избрано',
    'Select' => 'Избери',
    'ID' => 'ID',
    'Occupied' => 'Заето',
    'Passanger Name' => 'Име на пасажера',
    'Sorry we could not find the flight that you are looking for!' => 'Ако сте готови може да натиснете бутона под този текст!',
    'Available' => 'на разположение',
    'Selected' => 'избрани',
    'Select' => 'изберете',
    'ID' => 'номер',
    'Occupied' => 'заети',
    'Passanger Name' => 'име на пътника',
    'Sign In manually' => 'Masuk tanpa google',
    'If you are done choosing the seat, you can click the button bellow' => 'Jika anda sudah selesai memilih kursi silahkan klik tombol di bawah',
    'Sign In' => 'Впиши се',
    'Forgot Password' => 'Lupa Kata Sandi',
    'Click Here' => 'Klik Disini',
    'Not a Member Yet' => 'Belum Jadi Member',
    'Register Here' => 'Daftar Disini',
    'Or Sign In with Google' => 'Masuk Melalui Google',
    'Password must contain the following' => 'Kata Sandi harus memenuhi syarat berikut',
    'A <b>lowercase</b> letter' => 'Mengandung huruf <b>kecil</b>',
    'A <b>capital (uppercase)</b> letter' => 'Mengandung huruf <b>kapital</b>',
    'A <b>number</b>' => 'Mengandung <b>angka</b>',
    'Minimum <b>8 characters</b>' => 'Minimum <b>8 karakter</b>',
    'Repeat Password'=> 'Ulang Kata Sandi',
    'Password' => 'Kata Sandi',
    'Already Have an Account' => 'Sudah mempunyai Akun',
    'Register' => 'Daftar',
    'Sign In here'=> 'Masuk di sini',
    'Or Sign Up with Google' => 'Daftar Melalui Google',

];