<?php
/**
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Home',
    'My-Trip' => 'My-Trip',
    'Check-In' => 'Check-in',
    'From' => 'From',
    'To' => 'To',
    'Profile' => 'Profile',
    'One-Way' => 'Sekali Jalan',
    'Round Trip' => 'Pulang-Pergi',
    'Departure Date'=>'Tanggal Keberangkatan',
    'Return Date'=>'Tanggal Kembali',
    'Passangers'=>'Penumpang',
    'Class'=>'Kelas',
    'Adults (12+ years)'=>'Dewasa (12+ Tahun)',
    'Child (2-11 years)'=>'Anak-anak (2-11 Tahun)',
    'Infant' => 'Infant',
    'SEARCH' => 'CARI'
];